version: '3.8'
services:
  fb_photo_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - fb_photo_service_db

  #  pastbook_queue:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    command: 'php artisan queue:work'
  #    depends_on:
  #      - pastbook_db

  fb_photo_service_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: fb_photo_service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33064:3306
