version: '3.8'
services:
  pastbook:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - pastbook_db

#  pastbook_queue:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: 'php artisan queue:work'
#    depends_on:
#      - pastbook_db

  pastbook_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: pastbook
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33060:3306
